pipeline {
agent none

stages {


stage('Back-end') {
  agent {
    docker { image 'maven:3.8.1-adoptopenjdk-11' }
  }
  steps {
    sh 'mvn --version'
  }
}

stage('Front-end') {
  agent {
    docker { image 'node:16-alpine' }
  }
  steps {
    sh 'node --version'
  }
}

stage('DB') {
  agent any
  steps {
    sh '''
    docker rm -f mysql || true

    docker run -d --name mysql \
      -e MYSQL_ROOT_PASSWORD=root \
      mysql:latest

    echo "Waiting for MySQL to start..."
    sleep 40

    docker ps

    docker exec mysql \
      mysql -u root -proot -e "SHOW DATABASES;" || echo "MySQL not ready"

    docker rm -f mysql
    '''
  }
}

}
}
