pipeline {
    agent any

    stages {
        stage('build') {
            steps {
                echo "Running on ${env.NODE_NAME}"
                sh 'hostname'
            }
        }

        stage('test') {
            steps {
                echo "Testing..."
            }
        }

        stage('deploy') {
            steps {
                echo "Deploying..."
            }
        }
    }
}