pipeline {
    agent { label 'DevServer' }

    parameters {
        choice(name: 'select_env', choices: ['dev', 'prod'])
    }

    environment {
        NAME = "jeeva"
    }

    tools {
        maven 'myMaven'
    }

    stages {

        stage('Build') {
            steps {
                dir('java') {
                    sh 'mvn clean package -DskipTests=true'
                    echo "Hello ${env.NAME}"
                }
            }
        }

        stage('Test') {
            parallel {
                stage('TestA') {
                    steps {
                        dir('java') {
                            echo "This is test A"
                            sh 'mvn test'
                        }
                    }
                }
                stage('TestB') {
                    steps {
                        dir('java') {
                            echo "This is test B"
                            sh 'mvn test'
                        }
                    }
                }
            }
        }

        stage('deploy_dev')
        {
            when {
                expression { params.select_env == 'dev' }
                beforeAgent true
                }
            agent { label 'DevServer' }
            steps{
                dir("java/")
                {
                    unstash "maven-build"
                }
                sh """
                ls target/
                java -jar target/*.jar
                """
            }
        }
    }

    post {
        success {
            dir("java/")
            {
                stash name: "maven-build",includes:"target/*.jar"
            }
        }
    }
}