pipeline {
    agent { label 'DevServer' }

    tools {
        maven 'myMaven'
    }

    stages {
        stage('build') {
            steps {
                dir('java') {   
                    sh 'mvn clean package'
                }
            }
        }
    }

    post {
        success {
            archiveArtifacts artifacts: '**/target/*.jar'
        }
    }
}